{{- if .Values.envForm.secrets }}
{{- range .Values.envForm.secrets }}
{{- if .secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretRef }}
  labels:
    {{- include "laforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Ajoutez ici les données de votre secret, par exemple :
  DB_PASSWORD: {{ .Values.envForm.secrets.secretData.database-password | quote }}
{{- end }}
{{- end }}
{{- end }}
